name: Parallel  Test Build
on: push
jobs:
  Add-To-Cart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
         command: npm run test:addToCart


      - name: Cypress Test Report
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome HTML Report - Add-To-Cart-Test
          path: cypress/reports/html   
   

  Register-User-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
         command: npm run test:register


      - name: Cypress Test Report
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome HTML Report - Register-Test
          path: cypress/reports/html   

  Search-Shirt-run:  
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
         command: npm run test:searchShirt  

      - name: Cypress Test Report
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome HTML Report - Search-Shirt-Test
          path: cypress/reports/html